import { Router } from 'express';
import multer from 'multer';
import { GoogleGenerativeAI, HarmCategory, HarmBlockThreshold } from '@google/generative-ai';

const router = Router();

// Configure Multer for in-memory file storage
const upload = multer({ storage: multer.memoryStorage() });

// --- Gemini API Setup ---
const API_KEY = process.env.GEMINI_API_KEY as string;
const genAI = new GoogleGenerativeAI(API_KEY);

const safetySettings = [
  { category: HarmCategory.HARM_CATEGORY_HARASSMENT, threshold: HarmBlockThreshold.BLOCK_NONE },
  { category: HarmCategory.HARM_CATEGORY_HATE_SPEECH, threshold: HarmBlockThreshold.BLOCK_NONE },
  { category: HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT, threshold: HarmBlockThreshold.BLOCK_NONE },
  { category: HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT, threshold: HarmBlockThreshold.BLOCK_NONE },
];

// Helper function to convert buffer to generative part
function fileToGenerativePart(buffer: Buffer, mimeType: string) {
  return {
    inlineData: {
      data: buffer.toString("base64"),
      mimeType
    },
  };
}

// --- API Endpoints ---

/**
 * POST /api/classify
 * Handles image classification.
 * Expects 'multipart/form-data' with an 'image' field.
 */
router.post('/classify', upload.single('image'), async (req, res) => {
  if (!req.file) {
    return res.status(400).send('No image file uploaded.');
  }

  try {
    const model = genAI.getGenerativeModel({ 
      model: "gemini-2.5-flash-preview-09-2025",
      safetySettings
    });

    const prompt = `You are an expert fashion archivist. Classify this clothing artifact. 
    Respond ONLY with a JSON object with this exact structure: 
    {"name": "...", "category": "...", "decade": "...", "style": "...", "description": "..."}.
    - name: A cool, catchy name for the item (e.g., "Vintage Denim Jacket").
    - category: One of [Tops, Bottoms, Outerwear, Footwear, Accessories, Full Body].
    - decade: Estimated decade (e.g., "1990s").
    - style: Primary style (e.g., "Grunge", "Minimalist", "Y2K").
    - description: A brief one-sentence description.
    `;

    const imagePart = fileToGenerativePart(req.file.buffer, req.file.mimetype);
    
    const result = await model.generateContent([prompt, imagePart]);
    const responseText = result.response.text();
    
    // Clean the response to ensure it's valid JSON
    const jsonResponse = responseText.replace(/```json/g, "").replace(/```/g, "").trim();

    // Send the raw JSON string back to the frontend
    res.status(200).json({ classificationText: jsonResponse });

  } catch (error) {
    console.error('Error classifying image:', error);
    res.status(500).send('Error classifying image.');
  }
});

/**
 * POST /api/generate
 * Handles image generation (image-to-image).
 * Expects 'application/json' with 'prompt' and 'imageBase64'.
 */
router.post('/generate', async (req, res) => {
  const { prompt, imageBase64 } = req.body;

  if (!prompt || !imageBase64) {
    return res.status(400).send('Missing prompt or imageBase64.');
  }

  try {
    const model = genAI.getGenerativeModel({
      model: "gemini-2.5-flash-image-preview",
      safetySettings
    });

    // Extract mime type and data from base64 string
    const match = imageBase64.match(/^data:(image\/[a-z]+);base64,(.+)$/);
    if (!match) {
      return res.status(400).send('Invalid base64 image format.');
    }
    
    const mimeType = match[1];
    const data = match[2];

    const imagePart = {
      inlineData: { data, mimeType }
    };

    const result = await model.generateContent([prompt, imagePart]);
    
    // Find the generated image part
    const generatedImagePart = result.response.candidates?.[0].content.parts.find(p => p.inlineData);

    if (!generatedImagePart || !generatedImagePart.inlineData) {
      throw new Error('No image generated by the model.');
    }

    // Send the base64 data of the *new* image back
    const newBase64Data = generatedImagePart.inlineData.data;
    res.status(200).json({ base64Image: newBase64Data });

  } catch (error) {
    console.error('Error generating image:', error);
    res.status(500).send('Error generating image.');
  }
});

export default router;